
-
  gather_facts: false
  hosts: "{{ hosts }}"
  name: "Disable Network Level Authentication"
  tasks:
    -
      name: "Disabling..."
      win_command: powershell.exe -
      args:
        stdin: (Get-WmiObject -class "Win32_TSGeneralSetting" -Namespace root\cimv2\terminalservices -ComputerName $env:computername -Filter "TerminalName='RDP-tcp'").SetUserAuthenticationRequired(0)
